services:
  app:
    build: .
    container_name: mailboard-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      CORS_ALLOWED_ORIGIN_1: ${CORS_ALLOWED_ORIGIN_1}
      CORS_ALLOWED_ORIGIN_2: ${CORS_ALLOWED_ORIGIN_2}
      CORS_ALLOWED_ORIGIN_3: ${CORS_ALLOWED_ORIGIN_3}
    # volumes:
    #   - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - postgresql
    networks:
      mailboard-network:
        aliases:
          - app

  ngrok:
    image: ngrok/ngrok:latest
    container_name: mailboard-ngrok
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: "http app:8080"
    depends_on:
      - app
    env_file:
      - .env
    networks:
      - mailboard-network

  postgresql:
    image: pgvector/pgvector:pg17
    container_name: mailboard-db
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: mailboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mailboard-network

volumes:
  postgres_data:

networks:
  mailboard-network:
    driver: bridge
    name: mailboard-unified-network
